{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggsignif
  version: {{ version|replace("-", "_") }}

source:
  fn: ggsignif_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggsignif_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggsignif/ggsignif_{{ version }}.tar.gz
  sha256: 7d1093d980eb16d8bad5af131f578ba7e129eda9a295d59d77c6c8866779047c

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=2.0.0
  run:
    - r-base
    - r-ggplot2 >=2.0.0

test:
  commands:
    - $R -e "library('ggsignif')"           # [not win]
    - "\"%R%\" -e \"library('ggsignif')\""  # [win]

about:
  home: https://github.com/const-ae/ggsignif
  license: GPL-3
  summary: Enrich your 'ggplots' with group-wise comparisons. This package provides an easy way
    to indicate if two groups are significantly different. Commonly this is shown by
    a bracket on top connecting the groups of interest which itself is annotated with
    the level of significance (NS, *, **, ***). The package provides a single layer
    (geom_signif()) that takes the groups for comparison and the test (t.test(), wilcox.text()
    etc.) as arguments and adds the annotation to the plot.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
